### ISSUE TITLE
The example in readme is not working

### ISSUE THREAD

**Issue by prrashi** [deep-compute/kwikapi.tornado#7]
```
root@pamidi-usa:~/exps# python3 kwik.py 
Traceback (most recent call last):
  File "kwik.py", line 4, in <module>
    from kwikapi.tornado import RequestHandler
  File "/usr/local/lib/python3.5/dist-packages/kwikapi/tornado/__init__.py", line 1, in <module>
    from .kwikapi_tornado import RequestHandler
  File "/usr/local/lib/python3.5/dist-packages/kwikapi/tornado/kwikapi_tornado.py", line 4, in <module>
    from kwikapi import BaseRequest, BaseResponse, BaseRequestHandler
ImportError: cannot import name 'BaseRequest'
```

**Comment by prashanthellina** [comment]
@RamanjaneyuluIdavalapati Can you check this out please?

**Comment by IdavalapatiRamanjaneyulu** [comment]
@prrashi, I am extremely sorry. I didn't noticed this issue.

But I hope the problem may be resolved as of now. Can you please check.

**Comment by jaswanth098** [comment]
This is working fine now, closing this
